### ISSUE TITLE
Unable to run builddbg command.

### ISSUE THREAD

**Issue by vishnunv0911** [lasersonlab/pepsyn#17]
The command line outputs "Aborted!" after running builddbg.

My shell input:

#Clean input file
input='input_orfs.fasta'
cat $input \
| pepsyn stripstop - - \
| pepsyn filterstop - - \
| pepsyn x2ggsg - - \
| pepsyn disambiguateaa - - \
> input_orfs.clean.fasta 

#Build De-bruijn graph
output='dbg.k20.pickle'
kmer_size=20
pepsyn builddbg -k $kmer_size input_orfs.clean.fasta $output

Am I doing something wrong? Any help would be greatly appreciated!

Note: I don't think there is an issue with the input file since I have used the other pepsyn commands to create a peptide library and it seems to work.

**Comment by laserson** [comment]
I can't tell what your actual input command was as the formatting is funny. Could you fix and also copy the exact error output?

**Comment by vishnunv0911** [comment]
Hi, sorry I didn't notice it got posted in a weird way.

My input command is,

pepsyn builddbg -k $kmer_size $input_orfs.clean.fasta $output

The error output is just, 

Aborted!

I can't seem to find any other log for it. I am very new to this so I might be doing something wrong.

**Comment by laserson** [comment]
Could you copy/paste exactly what you see please?

Also, what do you get if you run `echo $kmer_size`, `echo $input_orfs`, and `echo $output`? Finally, do you have networkx installed?

**Comment by laserson** [comment]
(also, if you can fence a block with three-backticks "```" to get it to render as code.)

**Comment by vishnunv0911** [comment]
I am attaching the bash scripts I am using for this. There are 2 files, one for the Phip-Seq workflow as given in the protocol:
https://www.nature.com/articles/s41596-018-0088-4

The file task_final.sh has the script as described in the protocol, so you can understand what I am trying to do on the command line. All the files mentioned here are in the working directory where the script is used. 

<img width="955" alt="task_final" src="https://github.com/lasersonlab/pepsyn/assets/97388208/a1b77275-3cdd-4a83-b2f5-b17f73b8182c">

The file taskdbg.sh is the one I am having errors with.

<img width="704" alt="taskdbg" src="https://github.com/lasersonlab/pepsyn/assets/97388208/c7f58186-25cf-4b6b-aa53-99a796744eac">

I run both of these by running "bash task_final.sh" on the command line.

I apologise I have not installed networkx.

**Comment by vishnunv0911** [comment]
> (also, if you can fence a block with three-backticks "```" to get it to render as code.)

I am unsure how to do this, but I will give it a try.

**Comment by vishnunv0911** [comment]
building dbg: 1it [00:00, 6944.21it/s]
Traceback (most recent call last):
   File "/root/miniconda3/bin/pepsyn", line 33, in <module>
     sys.exit(load_entry_point('pepsyn==0.4.1+5.ga596921',
'console_scripts', 'pepsyn')())
   File "/root/miniconda3/lib/python3.10/site-packages/click/core.py",
line 1128, in __call__
     return self.main(*args, **kwargs)
   File "/root/miniconda3/lib/python3.10/site-packages/click/core.py",
line 1053, in main
     rv = self.invoke(ctx)
   File "/root/miniconda3/lib/python3.10/site-packages/click/core.py",
line 1659, in invoke
     return _process_result(sub_ctx.command.invoke(sub_ctx))
   File "/root/miniconda3/lib/python3.10/site-packages/click/core.py",
line 1395, in invoke
     return ctx.invoke(self.callback, **ctx.params)
   File "/root/miniconda3/lib/python3.10/site-packages/click/core.py",
line 754, in invoke
     return __callback(*args, **kwargs)
   File
"/root/miniconda3/lib/python3.10/site-packages/pepsyn-0.4.1+5.ga596921-py3.10.egg/pepsyn/cli.py",
line 542, in builddbg
   File
"/root/miniconda3/lib/python3.10/site-packages/pepsyn-0.4.1+5.ga596921-py3.10.egg/pepsyn/dbg.py",
line 159, in fasta_handle_to_dbg
   File
"/root/miniconda3/lib/python3.10/site-packages/pepsyn-0.4.1+5.ga596921-py3.10.egg/pepsyn/dbg.py",
line 148, in name_seq_pairs_to_dbg
   File
"/root/miniconda3/lib/python3.10/site-packages/pepsyn-0.4.1+5.ga596921-py3.10.egg/pepsyn/dbg.py",
line 126, in update_debruijn_graph
AttributeError: 'DiGraph' object has no attribute 'add_path'


I installed networkx and used the same script. It gave me this error^

**Comment by laserson** [comment]
Looks like networkx has moved the `add_path` function elsewhere in a more recent version. I don't have time to maintain this package so I can't fix any of these issues at the moment.

**Comment by vishnunv0911** [comment]
okay no worries,
Thank you!
