### ISSUE TITLE
Selection of the codon usage table during the reverse translation step

### ISSUE THREAD

**Issue by RChGO** [lasersonlab/pepsyn#20]
Hi!
If T7 phages are used, would the reverse translation step from protein to DNA sequences still rely on the codon usage table of Escherichia coli, regardless of the origin of your Open Reading Frame (ORF), whether it's from fungi, chlamydia, or any other species?

**Comment by laserson** [comment]
If you're using phage that's expressing in E. coli, you probably want the sequences to be optimized for E. coli. But you could always implement a different table.
