### ISSUE TITLE
Confusion about `tile` and `pad`

### ISSUE THREAD

**Issue by PpGrApee** [lasersonlab/pepsyn#22]
Hi! I read the paper called "PhIP-Seq characterization of serum antibodies using oligonucleotide-encoded peptidomes" from 2018 by Divya Mohan et al. and study to use pepsyn. When i am running my data, i am confused about "pepsyn tile". I set TILESIZE=64
OVERLAP=7. In my protein data, there is a short peptide:"MLGNMNVFMAVLGIILFSGFLAAYFSHKWDD". After i run the pepsyn tile, i find this peptide is missing, there is no "MLGNMNVFMAVLGIILFSGFLAAYFSHKWDD" in my orf_tiles.fasta. 
Also, i have another question about "pepsyn pad". If my peptide is shorter than 64, will the aa add at the c-term influence the express of the protein? Because i have not add the stop codon at the end of the peptide.
This is my code:
TILESIZE=64
OVERLAP=7
cat protein/uniprotkb_proteome_UP000000625_AND_revi_2024_11_25.fasta \
	| pepsyn x2ggsg - - \
	| pepsyn tile -l $TILESIZE -p $OVERLAP - - \
	| pepsyn disambiguateaa - - \
	> orf_tiles.fasta
cat orf_tiles.fasta \
	| pepsyn pad -l $TILESIZE --c-term - - \
	> protein_tiles.fasta

Thanks in advance!

**Comment by laserson** [comment]
Hi @PpGrApee.

If you run `pepsyn tile -h`, you'll see that the docs include the following note:

```
    Note: this tool drops "incomplete/short" last tiles if the length/overlap
    setting does not allow a tiling to perfectly cover a sequence. We recommend
    using ``ctermpep`` to explicitly capture the last tiles.
```

For `pepsyn pad`, it adds a repeating pattern of `GSGG` up until the desired length. If an input peptide is longer than the requested length, I believe it just passes it through unmodified. This command will not add any stop codons.

Also note that this package is no longer being maintained.
